### PR TITLE
Feature : Adding a footer section into the web page #17

### PR DESCRIPTION
**Pull request by Arnab7456**
Feature: Adding a footer section to the web page #17

Add responsive Footer section
Mobile View
Screenshot 2024-10-17 204251

Web Page
Screenshot 2024-10-17 204300

### CODE REVIEW

**Comment by Arnab7456** [comment]
@subhadeeproy3902  Hey, could you please merge the pull request? I've completed the work as per the issue I raised.

**Review by subhadeeproy3902 — CHANGES_REQUESTED** [review]
Please rectify the UI, Its looking too dull and not to worthy. So please look into the UI and the responsiveness of the footer !

**Comment by Arnab7456** [comment]
can you elaborate on what you are looking for, like dark or Light Ui

**Comment by subhadeeproy3902** [comment]
> can you elaborate on what you are looking for, like dark or Light Ui

I said the UI must be good and responsive !. Currently it looks dull to me and make it in only light mode !

**Comment by Arnab7456** [comment]
new Light Ui Mobile & tab responsive theme added, make sure you upstream your code then check, because sometimes SS looks dull also

image

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 new Light Ui Mobile & tab responsive theme added, make sure you upstream your code then check, because sometimes SS looks dull also
> 
> image

image
A footer this i what I was talking about to have a really nice UI !
What you made is too simple... very simple one ... which doesnt fit with the UI we wanna build

**Comment by subhadeeproy3902** [comment]
> @Arnab7456 Please do the necessary changes within this week or else others asked me up if they can add footer. I cannot wait for one PR to be resolved this long !

You didnt change the necessary things. I am closing this PR

**Pull request closed without merging**
