### PR TITLE
services Page

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #125 

If You need any changes I will commit them in the same PR . PLease do not close it else I will loose all changes and files. Let me know what You need and I will gladly make all changes.

### CODE REVIEW

**Comment by subhadeeproy3902** [comment]
You should be providing the Images and Videos bro @inkerton

**Comment by inkerton** [comment]
Video is on the issue check out the related issue @subhadeeproy3902 #125

**Comment by subhadeeproy3902** [comment]
> Video is on the issue check out the related issue @subhadeeproy3902 #125

That is someone else's done website. I am talking about what you have done in the PR, Show that video or screenshot !

**Comment by inkerton** [comment]
> > Video is on the issue check out the related issue @subhadeeproy3902 #125
> 
> That is someone else's done website. I am talking about what you have done in the PR, Show that video or screenshot !

That is my work. That is not a website I used tailwind css to make it

**Comment by subhadeeproy3902** [comment]
> > > Video is on the issue check out the related issue @subhadeeproy3902 #125
> > 
> > 
> > That is someone else's done website. I am talking about what you have done in the PR, Show that video or screenshot !
> 
> That is my work. That is not a website I used tailwind css to make it

I dont know what its so difficult to give a image of what u have done in this PR, rather than giving an image of what u have done previously !

**Comment by inkerton** [comment]
From next time onwards I will attach the video or ss here in the PR.

**Pull request merged**
