### PR TITLE
Added Footer to the Website

### PR DESCRIPTION
**Pull request by mjgandhi2305**
image
Added footer to the website which closes the issue #88 

Please add labels hacktoberfest-accepted level-2 and gssoc-extd. 
If any changes then kindly comment.

### CODE REVIEW

**Review by subhadeeproy3902 — CHANGES_REQUESTED** [review]
image
this i what I was talking about to have a really nice UI !
What you made is too simple... very simple one ... which doesnt fit with the UI we wanna build

Take some inspiration .. I am not telling to build exactly the same !

**Comment by mjgandhi2305** [comment]
@subhadeeproy3902 give me three days.  Will build the best footer as per your requirements

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 give me three days. Will build the best footer as per your requirements

image

Another good example is this !

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902 give me three days. Will build the best footer as per your requirements

Its already 3 days @mjgandhi2305

**Pull request closed without merging**
