### PR TITLE
Build Contact Page #70

### PR DESCRIPTION
**Pull request by saurabh-dev-vns**
"Issue #70

The contact page has been added, and the UI is as per your preferences, which looks awesome.

Screenshot (27)
Screenshot (28)

### CODE REVIEW

**Comment by saurabh-dev-vns** [comment]
@subhadeeproy3902, please review the UI of the contact page and merge the PR.

**Review by subhadeeproy3902 — CHANGES_REQUESTED** [review]
Its too simple and my previous component is kinda used here ... So please change this contact us page a bit !

**Comment by subhadeeproy3902** [comment]
> Its too simple and my previous component is kinda used here ... So please change this contact us page a bit !

image

An example contact us page. I need a designer one !

**Comment by saurabh-dev-vns** [comment]
OK , I'll do changes in it

**Comment by saurabh-dev-vns** [comment]
@subhadeeproy3902, please review the UI of the contact page and merge the PR.

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902, please review the UI of the contact page and merge the PR.

Did see the deployed version.
I would like a bit of changes @saurabh-dev-vns 
That is an animated world map like the image i sent earlier. U can find it online in any UI components. and 

image

Currently its having no icons 

image

Make like this  and at the end of the page 

image

I will be happily giving Level 3 to this for ur hardwork dude !

**Comment by saurabh-dev-vns** [comment]
@subhadeeproy3902, please review the UI of the contact page and merge the PR.


https://github.com/user-attachments/assets/1626e64e-df75-4036-9a13-d934498532b4

**Comment by subhadeeproy3902** [comment]
> @subhadeeproy3902, please review the UI of the contact page and merge the PR.
> 
>  2024-10-20.20-29-06.mp4

image

@saurabh-dev-vns Use lucide icons (Shadcn's official icon library)
If u also can ... Make the world map a bit animated uk 🤩

**Comment by subhadeeproy3902** [comment]
@saurabh-dev-vns Please fix this. Then only I will be able to merge this PR

> > @subhadeeproy3902, please review the UI of the contact page and merge the PR.
> > 2024-10-20.20-29-06.mp4
> 
> image
> 
> @saurabh-dev-vns Use lucide icons (Shadcn's official icon library) If u also can ... Make the world map a bit animated uk 🤩 Rest we are good to go ... Great JOB !
Only thing restricting me the deployment fail bro :(

**Comment by saurabh-dev-vns** [comment]
@subhadeeproy3902 , issue is resolved.

**Pull request merged**
